### ISSUE TITLE
Does not work with Pony

### ISSUE THREAD

**Issue by ixlan** [bmabey/email-spec#159]
Maybe I'm doing something wrong here are my steps:
1) I added 'email_spec' and 'email_spec/cucumber' to the env.rb
2) Generated helpers
3) Have a step: And "bulletdl@yahoo.com" should receive an email
4) Alternatively, I tried a custom step with  Pony.should_receive(:deliver_signup).with("bulletdl@yahoo.com", "Confirmation")

I get an error: 
![screen shot 2015-01-05 at 11 50 07](https://cloud.githubusercontent.com/assets/6791828/5607869/cd6bda0e-94d1-11e4-9588-900f6fe07bd6.png)

Do I need to setup pony in  config/initializers/pony.rb? When I set it to send messages in test environment in pony.rb, I start to get real emails while test shows that email did not receive any mails.

**Comment by etagwerker** [comment]
@ixlan No, you don't need to setup Pony. This error was probably due to the lack of implementation in `email_steps.rb`

```
module EmailHelpers
  def current_email_address
    # Replace with your a way to find your current email. e.g @current_user.email
    # last_email_address will return the last email address used by email spec to find an email.
    # Note that last_email_address will be reset after each Scenario.
    last_email_address || "example@example.com"
  end
end
```

This is the default implementation provided by `email-spec` which should be customized by you. If you had used the address `example@example.com` it would work. 

A possible set of steps could be: 

```
# email_steps.rb
module EmailHelpers
  def current_email_address
    # Replace with your a way to find your current email. e.g @current_user.email
    # last_email_address will return the last email address used by email spec to find an email.
    # Note that last_email_address will be reset after each Scenario.
    if @current_user
      @current_user.email
    else
      @current_email_address || "example@example.com"
    end
  end
end

Given /^my email is "([^"]*)"$/ do |email|
  @current_email_address = email
end
```
