### ISSUE TITLE
Upgrade mail gem to 2.6.3+

### ISSUE THREAD

**Issue by nicolasgarnil** [bmabey/email-spec#161]
As per the article [36% smaller Rails memory footprint through Benchmarking](http://www.schneems.com/2014/11/07/i-ram-what-i-ram.html) versions of the `mail` gem below 2.6.3 contains a memory leak.

Must upgrade the dependency version to 2.6.3+.

**Comment by etagwerker** [comment]
@nicolasgarnil Done. Next time feel free to submit a pull request. :wink:
