### ISSUE TITLE
visit_in_email should use the mail that was received last?

### ISSUE THREAD

**Issue by jmuheim** [bmabey/email-spec#163]
I think it's counter-intuitive that `visit_in_email` doesn't load the last received email.

I can circumvent the problem by explicitly selecting the last received email like this:

```ruby
    open_last_email_for('donald@example.com')
    visit_in_email('Confirm my account!')
```

But I think this should be the standard behaviour?

**Comment by etagwerker** [comment]
@jmuheim I think it makes sense that you have to open the email and only then visit links in it.
